import React, { useState, useEffect } from 'react';
import Navigation from './components/Navigation';
import Gallery from './components/Gallery';
import ArtModal from './components/ArtModal';
import Generator from './components/Generator';
import About from './components/About';
import { Artwork, ViewState } from './types';

// Seed data for the gallery
const INITIAL_ARTWORKS: Artwork[] = [
  { id: '1', url: 'https://picsum.photos/id/1015/800/1000', title: 'Valley of Shadows', artist: 'Nature\'s Lens', year: '2023' },
  { id: '2', url: 'https://picsum.photos/id/1016/800/1000', title: 'Canyon Echoes', artist: 'Earth Walk', year: '2022' },
  { id: '3', url: 'https://picsum.photos/id/1040/800/800', title: 'The Castle Keep', artist: 'Historic Visions', year: '1890' },
  { id: '4', url: 'https://picsum.photos/id/106/800/1200', title: 'Fleur de Lis', artist: 'Botanical Dreams', year: '2024' },
  { id: '5', url: 'https://picsum.photos/id/116/800/600', title: 'Forgotten Rails', artist: 'Urban Decay', year: '2021' },
  { id: '6', url: 'https://picsum.photos/id/129/800/1000', title: 'Park Bench Solitude', artist: 'City Silence', year: '2023' },
  { id: '7', url: 'https://picsum.photos/id/145/800/800', title: 'Abstract Confusion', artist: 'Modern Mind', year: '2025' },
  { id: '8', url: 'https://picsum.photos/id/164/800/1000', title: 'Venetian Morning', artist: 'Water Ways', year: '1920' },
  { id: '9', url: 'https://picsum.photos/id/175/800/800', title: 'The Old Clock', artist: 'Timeless', year: '1950' },
];

const App: React.FC = () => {
  const [view, setView] = useState<ViewState>(ViewState.GALLERY);
  const [artworks, setArtworks] = useState<Artwork[]>(INITIAL_ARTWORKS);
  const [selectedArtwork, setSelectedArtwork] = useState<Artwork | null>(null);

  const handleArtCreated = (newArt: Artwork) => {
    setArtworks([newArt, ...artworks]);
    setView(ViewState.GALLERY);
  };

  return (
    <div className="min-h-screen bg-neutral-950 text-neutral-200 font-sans">
      <Navigation currentView={view} onViewChange={setView} />
      
      <main className="pt-24 pb-12">
        {view === ViewState.GALLERY && (
          <div className="animate-in fade-in duration-500">
            <header className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mb-8 flex items-end justify-between border-b border-neutral-800 pb-8">
              <div>
                <h1 className="text-4xl md:text-5xl font-serif text-white mb-2">Curated Collection</h1>
                <p className="text-neutral-500 font-light">Explore a fusion of captured reality and AI-dreamt visions.</p>
              </div>
              <div className="hidden sm:block text-right">
                <span className="block text-3xl text-gold-500 font-serif">{artworks.length}</span>
                <span className="text-xs uppercase tracking-widest text-neutral-600">Exhibits</span>
              </div>
            </header>
            <Gallery artworks={artworks} onArtworkClick={setSelectedArtwork} />
          </div>
        )}

        {view === ViewState.ATELIER && (
          <div className="animate-in slide-in-from-right duration-500">
            <Generator onArtCreated={handleArtCreated} />
          </div>
        )}

        {view === ViewState.ABOUT && (
          <div className="animate-in slide-in-from-bottom duration-500">
            <About />
          </div>
        )}
      </main>

      <footer className="border-t border-neutral-900 bg-neutral-950 py-12">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p className="text-neutral-700 text-sm">© {new Date().getFullYear()} Lumina Gallery. Art generated by Gemini.</p>
        </div>
      </footer>

      {selectedArtwork && (
        <ArtModal 
          artwork={selectedArtwork} 
          onClose={() => setSelectedArtwork(null)} 
        />
      )}
    </div>
  );
};

export default App;